language: node_js
node_js:
- '4.6'
before_script:
- npm install -g grunt-cli
script: grunt crossbrowser
env:
  global:
  - secure: HmsTWiwibB28awz5YIa3WmvhrDroWypjW7Hivn57Mz3tKW8J2/o30ZS06FmBROEEeaHGbVTyb0/DSfWS/mDGM8SweDXIV+xqwDLLUa/PdTgX4ROjUVofNHaHxzpUECnJJm8GV/euB8FgZNo9Wu1JBUCA/6HoLnCmlqK4cNSD5VY=
  - secure: e43D09e2fXuDcjw+P+1mtvpAnxb4730Wbtwd3Xb+xueoBQFP/cBdKx8Qy6f+kV9SXy7eVEzDC3MbxJtdtuYGlTY7oV3f3rmA00UhHokGbgw2SnEtCgzN7Eedtskz6ybbgy0FyMoF4CMg7R5mW+sxe40DbEyS2VdD19vOdXCNF9k=
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
